### ISSUE TITLE
Animation Editor Top bar not displaying correctly in FireFox

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#10]
![image](https://user-images.githubusercontent.com/59770668/109337704-3bfc7c80-7833-11eb-9c7d-26add92a7133.png)

**Comment by lix229** [comment]
Multi-browser support is something we are looking into.

But I cannot recreate this issue, please let me know if I missed something.

![Screen Shot 2021-03-23 at 3 33 22 PM](https://user-images.githubusercontent.com/35265304/112207092-1aea3a00-8bed-11eb-9000-18eb311eb5f3.png)
