### ISSUE TITLE
Animation Editor NaN ms

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#11]
Loaded up in firefox. Hit play.

![image](https://user-images.githubusercontent.com/59770668/109338357-29367780-7834-11eb-8fba-1e878de011ff.png)

**Comment by lix229** [comment]
This is the expected behavior because there is no keyframes loaded in memory.

Alternatively we can make it so that the play button is locked if that is the case, but which one is better is up to debate.
