### ISSUE TITLE
Animation Editor Uncaught TypeError: keyFrameList[0] is undefined

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#12]
In Firefox. 
Load Animation Editor. 
Immediately hit remove frame.

Console spits out Uncaught TypeError: keyFrameList[0] is undefined.

**Comment by lix229** [comment]
I cannot recreate this issue, with either Chrome or FireFox.

You can indeed remove the default 0ms keyframe, even with a warning message, and if the removed keyframe does not contain any meaningful transactions, this does not affect the animation at all.
