### ISSUE TITLE
Animation Editor, can't add a new frame that takes place after first frame

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#13]
When you start, the slider gives you a range of possible ms, but when you add a new frame, the slider's maximum becomes that frame's ms, so you can't make another frame later than that one.

**Comment by lix229** [comment]
You can by simply input values in the Frametime textbox, and this is expected behavior.

The silder is meant to give a rough idea of where the new keyframe will be inserted in an existing animation.

That being saild, the slider is likely to be gone as it is indeed wacky to work with.
