### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by KristieTom12** [lix229/UnityRuntimeImport#16]
As of commit [4608596](https://github.com/lix229/UnityRuntimeImport/commit/4608596d964e179958f49bf28304d1738860e78f) there is no release notes,

With games you want to have versioning and a list of what's in each patch and release such that users know what's changed when they upgraded their game.

Therefore include the following

- [ ] release notes page in the game
- [ ] release notes in the repository. This can be auto generated using [release-please github action](https://github.com/googleapis/release-please)

**Comment by lix229** [comment]
This is not a video game, but you have a great point.
