### ISSUE TITLE
Inability to label issues

### ISSUE THREAD

**Issue by KristieTom12** [lix229/UnityRuntimeImport#17]
Current layout:
![image](https://user-images.githubusercontent.com/34824500/109357111-ab806500-784f-11eb-98f1-82d5dc3f1882.png)

Good open source software practice is to allow all users to create issues and label the issue as bug request, feature, discussion, etc.

i.e. in the [GitHub documentation](https://docs.github.com/en/github/managing-your-work-on-github/managing-labels)

**Comment by lix229** [comment]
Added an issue template, thanks for the advise.
