### ISSUE TITLE
"Import" does not work while testing the Animation Editor

### ISSUE THREAD

**Issue by lim147** [lix229/UnityRuntimeImport#2]
After I click on the "Import" tab, I was expecting a folder navigation window props out where I can select the local animation txt file. However nothing happens.

**Comment by zhouh46** [comment]
Thanks for the feedback! 
I've merged the code with those two functions into the repo, which was caused by conflicts before, and they should be fine now!

**Comment by lix229** [comment]
This should have been fixed.
