### ISSUE TITLE
Animation Editor - Scrubber cannot be interacted with after clicking "Update Keyframe" with only one keyframe

### ISSUE THREAD

**Issue by Gregory-Kitching** [lix229/UnityRuntimeImport#21]
After clicking "Update Keyframe" on the default keyframe with no other keyframes present and closing both dialogue boxes, the cursor turns into a hand when hovering over the scrubber but the scrubber cannot be dragged.

![Screenshot (41)](https://user-images.githubusercontent.com/79662360/110024212-19b7a280-7cfc-11eb-84a7-dbef764375d6.png)

Reuploading this issue because I originally submitted it under the wrong account.

**Comment by lix229** [comment]
This is the expected bahavior, as if you only have one keyframe, the range of the slider is allowed to go is only 1.
