### ISSUE TITLE
Animation Editor - Possible to add negative value for frametime

### ISSUE THREAD

**Issue by Gregory-Kitching** [lix229/UnityRuntimeImport#22]
Nothing stops the user from entering a negative value into the timeframe field. The program will even still compile animation files with negative timeframes.

![Screenshot (39)](https://user-images.githubusercontent.com/79662360/110023992-cfcebc80-7cfb-11eb-83c4-9d011935463d.png)

![Screenshot (40)](https://user-images.githubusercontent.com/79662360/110023998-d1988000-7cfb-11eb-99d0-51bc9d095b88.png)

Reuploading this issue because I originally submitted it under the wrong account.

**Comment by lix229** [comment]
Having nagative values in keyframes are actually okay, although it might not be compatible when you attatch this animation to an object in Unity.

i.e. Scale an object in x axis to -3 means it will compress the object in x axis, and extend it to 3 times the size in -x direction.
