### ISSUE TITLE
Animation Editor outputs data in wrong format

### ISSUE THREAD

**Issue by Gregory-Kitching** [lix229/UnityRuntimeImport#23]
The text output by the editor upon clicking "export" differs from that found in the included tests. Copying the output into SampleAnim.txt and running the game results in nothing happening: the cube stays still and no error message is put out. The output can be made to work if edited manually to match the format of the included tests.

![Screenshot (31)](https://user-images.githubusercontent.com/79662360/110023584-52a34780-7cfb-11eb-94d5-e55cd1fe52ef.png)
The unaltered format of the output.

![Screenshot (27)](https://user-images.githubusercontent.com/79662360/110023629-62229080-7cfb-11eb-9e2c-4593f4a58500.png)
Nothing happens.

![Screenshot (38)](https://user-images.githubusercontent.com/79662360/110023647-68b10800-7cfb-11eb-9fc9-dfee59a89f84.png)
Manually edited version of the output, which does work. Note the different order of the transform, rotation and translation components.

Reuploading this issue because I originally submitted it under the wrong account.

**Comment by lix229** [comment]
This is now fixed, outputting in correct format now.
