### ISSUE TITLE
Wiki - 1.3 should go before 1.2

### ISSUE THREAD

**Issue by Gabriel-Gebril** [lix229/UnityRuntimeImport#24]
2019.4.8f1 LTS is hard to find unless you have already imported the sample project. Should have testers add the sample project first then install 2019.4.8f1 LTS from the add project dialogue.

**Comment by lix229** [comment]
May I ask what exactly does it mean by hard to find?

- The sample project should run fine on anything future version of Unity after 2019.4.8f1 LTS. This is mentioned mostly for users coming from an older version of Unity. i.e. The current recommaned version is 2019.4.21f1 LTS which should be perfectly okay.
- I believe you should install some versions of Unity first, then simply select the version you want the project to run on from the launch menu.
- If you want to report a bug that only occurs on certain versions of Unity, that is fine, too. :)

Hope this answers some of your issues. Let me know if I get the right idea. Othewise if there is nothing else I will close this issue.
