### ISSUE TITLE
Animation editor - Need input validation

### ISSUE THREAD

**Issue by immanuel-odisho** [lix229/UnityRuntimeImport#31]
repro:
1. Add the framtime with anything but a number
2. Click on add keyframe
3. Click Ok

Observation:
Keyframe sucessfully added with frametime as NaN
![1](https://user-images.githubusercontent.com/35702189/110027886-8c2a8180-7d00-11eb-973a-7b443a779a35.PNG)

Expectation:
Frametime should not accept NaN

**Comment by lix229** [comment]
File input is now fixed with input validation.
