### ISSUE TITLE
Scroll bar at bottom of Animation Editor does not work 

### ISSUE THREAD

**Issue by immanuel-odisho** [lix229/UnityRuntimeImport#32]
Repro:
1. Make a keyframe with normal input
2. Add Keyframe
3. Move scroll scroll at bottom of screen

Observation:
Scroll bar does not work
![1](https://user-images.githubusercontent.com/35702189/110028234-00652500-7d01-11eb-85bf-92ae3d408289.PNG)

Expectation:
Scroll bar should work or let the user know why it is not working

**Comment by lix229** [comment]
The scubber will be replaced with a different menu, as it really does not want to work.
