### ISSUE TITLE
Animation Editor no longer updates after invalid input

### ISSUE THREAD

**Issue by immanuel-odisho** [lix229/UnityRuntimeImport#33]
Repro:
1. Add keyframe with no inputs except translation as x = 10000, y = 10000, z = 10000;
2. Try to update keyframe with new settings

Observation:
Animation cannot recover
Expectation:
User should be able to cover animation editor if in broken state.
![2](https://user-images.githubusercontent.com/35702189/110028589-6ce02400-7d01-11eb-95e7-258e8e054281.PNG)

**Comment by lix229** [comment]
This is now fixed.
