### ISSUE TITLE
Frametime scroll does not match input field value Animation Editor

### ISSUE THREAD

**Issue by immanuel-odisho** [lix229/UnityRuntimeImport#35]
Repro:
1. Move the scroll button on the bottom to update frametime value
2. Frametime value should update
3. Click on Play

Observation:
Scroll feature crashes and resets to 4.07 and the scroll bar cannot be changed anymore
Expectation:
Scroll should match the input of frametime and work all times

**Comment by lix229** [comment]
The scrubber is known to be buggy, and there is not really a way around it, will replace it with something else in the next update.
