### ISSUE TITLE
NaN is accepted input for Translation

### ISSUE THREAD

**Issue by immanuel-odisho** [lix229/UnityRuntimeImport#38]
Repro:
1. Add a string as input for Translate3D values
2. Click on Add keyframe
3. Click on Export

Observation:
Input is accepted
Expected:
NaN should not be accepted for Translate3D
![3](https://user-images.githubusercontent.com/35702189/110029914-0f4cd700-7d03-11eb-9800-132dc0d54535.PNG)
![5](https://user-images.githubusercontent.com/35702189/110029916-0fe56d80-7d03-11eb-9be9-f481732de308.PNG)

**Comment by lix229** [comment]
Duplicate of #31
