### ISSUE TITLE
Runtime Import Module - First Frame set using 13 commas causes out of bounds error

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#39]
### Description:
I noticed that when editing the SampleAnim.txt file, if I remove the 14th comma from the line that defines the first frame, I get an index out of range exception

### Environment:
Device: Macbook Pro 2015

### Steps to Reproduce:
1. Edit SampleAnim.txt to the following (notice how there's only 13 commas in the second line): 
```
Default,1,NA
1,Obj,Default,0,0,0,0,0,0,0,0,0,1,1
1,Default,1000,0,0,0,0,180,180,180,3,3,3
1,Default,2000,0,0,0,0,360,360,360,5,5,5
1,Default,3000,0,0,0,0,540,540,540,3,3,3
1,Default,4000,0,0,0,0,720,720,720,1,1,1
```

2. Press play

### Actual Result:

Index Out of Range Exception:

![image](https://user-images.githubusercontent.com/25377291/110245150-0a209f80-7f30-11eb-8055-a8420f29a3bd.png)

### Expected Result:

Expected this to be handled gracefully

**Comment by lix229** [comment]
Not sure what this is supposed to mean.

If you manually cut off an entry, you essentially corrupts the data, of course Unity will throw you an error.
