### ISSUE TITLE
Animation editor - Better error/warining messages

### ISSUE THREAD

**Issue by lim147** [lix229/UnityRuntimeImport#4]
I tried to add frames several times but failed while receiving this message. I am not sure how to debug it. Was it because I left some field blank or something? 
<img width="1140" alt="Screen Shot 2021-02-25 at 2 18 21 PM" src="https://user-images.githubusercontent.com/35234798/109205735-01cca580-7775-11eb-9e83-bd5141524508.png">

**Comment by zhouh46** [comment]
Thanks for the feedback!
Yes, you have to have at least one of the three transformation to add a keyframe (Rotation, Scale or translate(location)).

**Comment by lix229** [comment]
This is now fixed.
