### ISSUE TITLE
Runtime Import Module - Relevance of First Frame Unclear

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#40]
### Description:
I noticed that if I enter incorrect values to the line that defines the first frame, the animation still runs and I get no indication that I've entered wrong information. Even if I remove this line entirely, the animation still runs. Thus, it's unclear to me the purpose of this frame and how it is affecting the animation.

### Environment:
Device: Macbook Pro 2015

### Steps to Reproduce:
1. Edit first frame (second line) of SampleAnim.txt with incorrect values: 
```
Default,1,NA
1,Obj,Default,a,a,a,a,a,a,a,a,a,a,a,a
1,Default,1000,0,0,0,0,180,180,180,3,3,3
1,Default,2000,0,0,0,0,360,360,360,5,5,5
1,Default,3000,0,0,0,0,540,540,540,3,3,3
1,Default,4000,0,0,0,0,720,720,720,1,1,1
```
2. Press play
3. Remove first frame entirely:
```
Default,1,NA
1,Default,1000,0,0,0,0,180,180,180,3,3,3
1,Default,2000,0,0,0,0,360,360,360,5,5,5
1,Default,3000,0,0,0,0,540,540,540,3,3,3
1,Default,4000,0,0,0,0,720,720,720,1,1,1
```
4. Press play

### Actual Result:

No indication that I've entered incorrect values, and animation still runs.

### Expected Result:

Some message that I've entered the first frame information incorrectly

**Comment by lix229** [comment]
The first line specifies the name of the object that this animation will be attached to, as well as the first keyframe (at 0ms by defualt) , that is why it has 1 more entry than the rest of the keyframes.

If you remove it, this should not work in Unity, but it would work fine in the Animation editor, as it treats it as the first keyframe was at 0ms with no transitions.

Again, manually editing the data can be fun, but if you do this you are at risk of corrupting the data, and there is really nothing I can do to stop you, as I have no idea what kind of modification will be done.
