### ISSUE TITLE
Animation Editor - Initial Frame Time not Indicated

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#44]
### Description:
When loading up the webpage for the first time, there's no indication if the starting frametime is actually 0ms. Only after moving the scrubber does a frametime appear

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open the Animation Editor 

### Actual Result:

No indication of initial frametime:

![image](https://user-images.githubusercontent.com/25377291/110250738-edde2c00-7f4a-11eb-9da7-905ea0277f1e.png)

### Expected Result:

I would expect the initial frametime to show as "0"

### Severity: Medium

**Comment by lix229** [comment]
This is expected behavior, that indicates no data was loaded at this moment.

Indeed a keyframe at 0ms is created by default, but it is measly a placeholder.
