### ISSUE TITLE
Animation Editor - UI inconsistency with buttons.

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#45]
### Description:
When loading up the webpage for the first time, the button at the bottom of the sidebar reads "Add Keyframe here" but after moving the scrubber it oddly changes to simply "Add keyframe".

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open the Animation Editor 
2. Move the scrubber

### Actual Result:

Initial:

![image](https://user-images.githubusercontent.com/25377291/110250873-b6bc4a80-7f4b-11eb-918c-7df293aa2c79.png)

After moving scrubber:

![image](https://user-images.githubusercontent.com/25377291/110250867-adcb7900-7f4b-11eb-98c8-9a21b9362612.png)

### Expected Result:

I would expect the naming to be consistent; moving the scrubber should not change the name of the button

### Severity: Low

**Comment by lix229** [comment]
This is now fixed.
