### ISSUE TITLE
Animation Editor - New Buttons Appear Simply By Moving Scrubber

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#46]
### Description:
When loading up the webpage for the first time, there is a single button at the bottom of the sidebar labeled "Add Keyframe here". However, after simply moving the scrubber to the right and then back to the start, two new buttons appear, labeled "Update keyframe" and "Remove Keyframe" respectively.

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open the Animation Editor 
2. Move scrubber to the right
3. Move scrubber back to the beginning

### Actual Result:

Initial:

![image](https://user-images.githubusercontent.com/25377291/110250873-b6bc4a80-7f4b-11eb-918c-7df293aa2c79.png)

After moving scrubber to the right and back:

![image](https://user-images.githubusercontent.com/25377291/110250998-64c7f480-7f4c-11eb-8c43-d582c38b2e4f.png)

### Expected Result:

I would expect nothing to change by simply moving the scrubber. From the new buttons, it looks as if the application thinks I've added a keyframe, when in reality all I did was move the scrubber.

### Severity: Medium

**Comment by lix229** [comment]
This is expected behavior as there is a keyframe at 0ms by default.

User input by moving the scrubber triggers the editing procedue as this keyframe being loaded into editing menu.

That being said, the slider will be gone soon.
