### ISSUE TITLE
Animation Editor - Magnitude of X,Y,Z Rotation Values is Irrelevant

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#48]
### Description:
I noticed that the size of the x,y, and z rotation values has no affect on the animation except for the 0 value which makes it so the particular axis is not affected.

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open the Animation Editor 
2. Set frametime to 500ms
3. Set `z` value to 1
4. Set `deg` value to 90
5. Update keyframe
6. Press play
7. Observe rotation
8. Scrub to 500ms to edit keyframe
9. Set `z` to 50
10. Repeat steps 5 - 7

### Actual Result:

Regardles of setting `z` value to 1 or 50, rotation animation is the same

### Expected Result:

It would be expected that changing the rotation values would impact the animation but it does not seem to be the case

### Suggestion:

Change the x, y, z rotation values to be boolean since it seems that the only relevant values are 0 and non 0 values. This would eliminate confusion as to what the x,y, and z values represent. It is clear that they simply set the animation to on and off for the particular axis they are set for and the UI should reflect this.

### Severity: Medium

**Comment by lix229** [comment]
The documentation suggests that the `x`, `y`, `z` values for rotation indicates the coordinate of the center point that the object will rotate around, with unit being pixel.

Thus a slight change, i.e. 1 pixel, will by design yield little to none visible change.
