### ISSUE TITLE
Animation Editor - Editing Frametime Clears All Fields

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#49]
### Description:
When filling out the fields in the sidebar, I noticed that if I go back to edit the Frametime field after adding in values for the other fields, all of my inputs are lost

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open the Animation Editor 
2. Set frametime to 500ms
3. Set `z` value to 1
4. Go back to frametime field and hit backspace to change value from 500ms to 50ms

### Actual Result:

`z` value is reset after editing the frametime value.

Before edit:

![image](https://user-images.githubusercontent.com/25377291/110253794-2e917180-7f5a-11eb-93b6-229be26547bd.png)

After Edit:

![image](https://user-images.githubusercontent.com/25377291/110253805-3bae6080-7f5a-11eb-9425-b5ccc918faeb.png)

### Expected Result:

I should expect that changing the frametime field should not affect the other fields that I have already filled out. This makes it really inconvenient to edit a keyframe if all I want to do is change the frametime

### Severity: Medium

**Comment by lix229** [comment]
If not submitted, one cannot preview the animation at all.

Thus I do not see the rational behind going to a different frametime and then go back to enter more values, as no further information can be obtained in the process to justify this action.
