### ISSUE TITLE
Animation Editor - Google Chrome UI elements broken/in wrong position

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#51]
### Description:
At regular 100% zoom upon opening the index.html in chrome, the elements on the top and bottom show up in incorrect positions.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor

### Actual Result:
![image](https://user-images.githubusercontent.com/29803319/110259584-5b538200-7f76-11eb-8b92-53989fb152c3.png)

### Expected Result:
Top bar elements should be inline and animation keyframe scroll bar should be at the bottom.

**Comment by lix229** [comment]
Duplicate of #5
