### ISSUE TITLE
[Animation Editor] Choppy Playback on Firefox

### ISSUE THREAD

**Issue by Gabriel-Gebril** [lix229/UnityRuntimeImport#53]
When playing an animation in Firefox the object doesn't so much "animate" as it slideshows
Environment:
Windows, Firefox
Steps to reproduce:
- Navigate to the animation editor in firefox
- press play

**Comment by lix229** [comment]
I cannot reproduce this error with 87.0 (64-bit) on macOS LTS.

If anything consistently triggers performance issue pleasse let me know.
