### ISSUE TITLE
[Animation Editor] Large scale value causes screen to become purple

### ISSUE THREAD

**Issue by Gabriel-Gebril** [lix229/UnityRuntimeImport#54]
Adding a keyframe with a large scalar value makes the object disappear and turns the screen purple.

![image](https://user-images.githubusercontent.com/16761051/110261575-bbe6bd00-7f7e-11eb-8729-8b8f4ba5eaca.png)

Environment:
Windows, Firefox

Steps to reproduce:
- Navigate to Animation Editor
- Set the scale above 1000
- Add the keyframe

**Comment by lix229** [comment]
Duplicate of #1
