### ISSUE TITLE
Animation Editor - end of scroll bar does not match end of animation

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#55]
### Description:
Whenever the scroll bar is moved, instead cube reflecting the specific frametime's values, an offset is introduced by the amount the scroll bar is moved by, changing the true end of the animation to somewhere in the middle of the bar

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
Put in any settings/frametime
press play
pause at any point
move the scroll bar's tracking point somewhere else along the bar
press play again

### Actual Result:
This is now the start and end point (animation restarts at this point on the bar) after moving the bar's tracking point after pausing the animation:
![image](https://user-images.githubusercontent.com/29803319/110263915-120b2e80-7f86-11eb-99e0-c9f0bcdfae3e.png)

### Expected Result:
Animation should move to that newly selected time's position.

**Comment by lix229** [comment]
The slider is known to be wacky at times, will be replaced with something else.
