### ISSUE TITLE
Animation Editor - keyframe added confirmation dialogue even on errored inputs

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#56]
### Description:
Whenever no transformations are added but a keyframe with a correct frametime is added, the user still gets a "keyframe added" confirmation dialogue before the error pops up.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
Put in any frametime, no other settings
add keyframe

### Actual Result:
First, a popup shows a new frame has been added
![image](https://user-images.githubusercontent.com/29803319/110264407-3adff380-7f87-11eb-9f0f-816698cd71c7.png)
Only after the user presses "OK", an error appears showing an issue with the inputs:
![image](https://user-images.githubusercontent.com/29803319/110264479-5d720c80-7f87-11eb-9742-c56dff5cf58c.png)

### Expected Result:
Only an error should pop up (the second image), not a confirmation dialogue showing a keyframe was added

**Comment by lix229** [comment]
This is now fixed.
