### ISSUE TITLE
Animation Editor - Nav bar not working

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#64]
### Description:
Clicking the button elements "Animation Editor" or "Home" (The cursor changes to a button cursor when hovering over them. These 2 buttons that normally would be meant to bring the user home, which should normally refresh the page if they are already home, else bring them to different webpage views) does not do anything.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
press the "Animation Editor" or "Home" buttons

### Actual Result:
nothing
### Expected:
Refresh the page
### Severity: Low

**Comment by lix229** [comment]
This is now fixed.
