### ISSUE TITLE
Able to add characters as values for rotation

### ISSUE THREAD

**Issue by IndiW** [lix229/UnityRuntimeImport#69]
# Severity
Low

# Environment
Windows 10 Pro, Firefox

# Steps to recreate
Start Web app. Input letters for rotation input and add keyframe.

# Expected behavior
Invalid inputs should not be allowed to be added as keyframe.

# Actual Behavior
Notification pops up that says new frame is added. The frame exists but does not do anything.

![image](https://user-images.githubusercontent.com/45280177/110349433-b467f800-8000-11eb-8d5b-221ae82402aa.png)

**Comment by lix229** [comment]
Duplicate of #31
