### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#7]
Default,1,NA
1,Obj,Default,0,0,0,0,0,0,0,0,0,1,1,1
1,Test,Default,1000,0,4,4,0,180,180,1800,0,0,0
1,Default,2000,0,0,0,0,180,360,360,5,5,5
1,Default,3000,0,0,0,0,540,540,540,3,3,3
1,Default,4000,0,0,0,0,720,720,720,1,1,1

IndexOutOfRangeException: Index was outside the bounds of the array.
LoadAnim.parseLines (System.Collections.Generic.List`1[T] data) (at Assets/Scripts/LoadAnim.cs:138)
LoadAnim.loadFile (System.String filePath) (at Assets/Scripts/LoadAnim.cs:71)
LoadAnim.Update () (at Assets/Scripts/LoadAnim.cs:31)]

Might just want to fail gracefully.

**Comment by lix229** [comment]
The data is corrupted, namely in third line:
```
1,Test,Default,1000,0,4,4,0,180,180,1800,0,0,0
     ^ Extra input arguments
```

Where `Test` is undefined and unexpected in Animation declaration `Default`.
If this is not triggered by manually editing the file, please let me know how to reproduce it.
