### ISSUE TITLE
Unicode AnimationName

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#8]
𝖉𝖊𝖋𝖆𝖚𝖑𝖙,1,NA
1,Head,𝖉𝖊𝖋𝖆𝖚𝖑𝖙,0,0,0,0,0,0,0,0,0,1,1,1
1,𝖉𝖊𝖋𝖆𝖚𝖑𝖙,1000,0,4,4,0,180,180,1800,0,0,0
1,𝖉𝖊𝖋𝖆𝖚𝖑𝖙,2000,0,0,0,0,180,360,360,5,5,5
1,𝖉𝖊𝖋𝖆𝖚𝖑𝖙,3000,0,0,0,0,540,540,540,3,3,3
1,𝖉𝖊𝖋𝖆𝖚𝖑𝖙,4000,0,0,0,0,720,720,720,1,1,1

Doesn't move the cube. Should it?

**Comment by lix229** [comment]
Of course it should not... A valid animation data file should be plain text without extra encoding as explained in the documentation. That is part of the whole point of using plain text, for better compatibility and readablity without needing extra  tools.
